Greeting.create(message: 'Good Morning!')
Greeting.create(message: 'Guten Morgen!')
Greeting.create(message: 'Buenos Dias!')
Greeting.create(message: 'Buongiorno!')
Greeting.create(message: 'Ohayou Gozaimasu!')
